### ISSUE TITLE
uses assigned IP addresses instead of reserved internal ranges

### ISSUE THREAD

**Issue by wardi** [JVickery-TBS/og-cli#1]
Setting up my first project assigned 100.0.0.0/16 to the docker virtual network. This is a public assigned range for Verizon.

```
NetRange:       100.0.0.0 - 100.19.255.255
CIDR:           100.0.0.0/12, 100.16.0.0/14
NetName:        V4-VZO
NetHandle:      NET-100-0-0-0-1
Parent:         NET100 (NET-100-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       AS19262
Organization:   Verizon Business (MCICS)
RegDate:        2010-12-28
Updated:        2022-05-31
Ref:            https://rdap.arin.net/registry/ip/100.0.0.0
```

A cursory look at docker-og makes me think these scripts might assign any ${OCTET}.0.0.0/16 to the docker network (definitely could cause network problems). Stick to the [private network ranges](https://en.wikipedia.org/wiki/Private_network) when assigning addresses for internal networks.

**Comment by JVickery-TBS** [comment]
@wardi ahhh okay thanks! Should be an easy change, I will just change the usage of the OCTET renting from `$OCTET.0.0.1` to `192.168.$OCTET.1` and that should solve those issues.

**Comment by wardi** [comment]
bonus points for checking that there aren't already routes for IPs in that range (192.168.0.* and 192.168.1.* are really common for home routers)

**Comment by JVickery-TBS** [comment]
@wardi it has a pool from 1-254. So I could just remove the `1` from the pool so the IP addresses will only ever be `192.168.[2-254].*`

**Comment by wardi** [comment]
or pick one of the 172.[17-31] range, those seem to be chosen less often by default

**Comment by JVickery-TBS** [comment]
This should now be resolved(ish) with the following commits on docker og:

- https://github.com/open-data/docker-og/commit/9f52fcf66e20f5a0ff8399bc4d190cc036077826
- https://github.com/open-data/docker-og/commit/a141179e9c4e7a13ab26866f3b6330658e551f7b
- https://github.com/open-data/docker-og/commit/576f67bef2bb76efbe446aea64f66abb44ade23e

And the output has been updated for the `info` subcommand for the `og` command:

- https://github.com/JVickery-TBS/og-cli/commit/0f2eb3e362f062c3ffe116eaf90dda82407b4303
- https://github.com/JVickery-TBS/og-cli/commit/26c8ce0a6913b1088a4b0bbae0791cdddab4e81e
